#!/usr/bin/env bash
# Performs dig on a url and gets the DNS info

custom_dig() {
    # digs the url passed to it and parses result into a human friendly form
    readarray -t -d $'\t' digInfo < <(printf '%s' "$(dig "$1" | grep -A1 'ANSWER SECTION' | awk '!(/^;/) { print }' | awk '/^[a-zA-Z]/ { print }')")

    echo "The subdomain $SUBDOMAIN is a ${digInfo[3]} record and points to ${digInfo[4]}"

    return 0
}

DOMAIN=$1
SUBDOMAIN=$2

if [ ! "$SUBDOMAIN" ]; then
    declare -a SUBDOMAINS=("www" "lb-01" "web-01" "web-02")
    for SUBDOMAIN in "${SUBDOMAINS[@]}"; do
	custom_dig "$SUBDOMAIN.$DOMAIN" 
    done
else
    custom_dig "$SUBDOMAIN.$DOMAIN"
fi
