#!/usr/bin/env bash
# Configure an NGINX server

# Install nginx
apt-get -y update && apt-get install nginx -y

# Create index.html file
touch /var/www/html/index.html

# Add content to the file
echo "Hello World!" > /var/www/html/index.html

# Start the service
service nginx restart
