#!/usr/bin/env bash
# Debug nginx server, makes sure it listens on port 80

sed -i.bak 's/8080/80/g' /etc/nginx/sites-available/default

# Recreate symbolic link
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

service nginx restart