#!/usr/bin/env bash
# This script displays "Best School" ten times
COUNT=0
while [ $COUNT -le 20 ]
do
    echo $COUNT
    case $COUNT in
	4) echo "bad luck from China";;
	9) echo "bad luck from Japan";;
	17) echo "bad luck from Italy";;
    esac
    COUNT=$((COUNT + 1))
done
