#!/usr/bin/env bash
# List of commands to setup UFW to block all incoming traffic excepts
# those going through TCP ports 22, 443, & 80.

sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh
sudo ufw enable

sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw allow 22/tcp
