#!/usr/bin/env bash
# This script changes some info in the /etc/hosts file
cp /etc/hosts ~/hosts.new
sed -i 's/\b127.0.0.1\b/127.0.0.2/' ~/hosts.new
sed -i '1s/^/8.8.8.8 facebook.com\n/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
