#!/usr/bin/env bash
# Debug an nginx server and set it up to run as nginx user instead
sudo chmod u+rw /etc/nginx/nginx.conf
sudo sed -i.bak 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sudo sed -i.bak 's/80/8080/g' /etc/nginx/sites-available/default
sudo pkill apache2
sudo -u nginx service nginx restart
